#!/bin/bash

# Script generated by ChatGPT

# Check if the correct number of arguments is provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <file_to_add.v> <target_file.v>"
    exit 1
fi

# Assign command line arguments to variables
file_to_add="$1"
target_file="$2"

# Check if the files exist
if [ ! -f "$file_to_add" ] || [ ! -f "$target_file" ]; then
    echo "Error: One or both files do not exist!"
    exit 1
fi

# Use awk to insert content before "endmodule" and write the result to a temporary file
temp_file="$(mktemp)"
awk -v add_file="$file_to_add" '
    /endmodule/ {
        while((getline line < add_file) > 0) {
            print line
        }
        close(add_file)
        print "" # New line
    }
    { print }
' "$target_file" > "$temp_file"

# Overwrite target file with temp file
mv "$temp_file" "$target_file"
